server:
  port: 8080
  undertow:
    direct-buffers: true

spring:
  application:
    name: "awpaas-repository"
  jackson:
    serialization:
      indent_output: true
  security:
    basic:
      enabled: true
    user:
      name: root
      password: Awpaas1020.cn

security:
  basic:
    enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    time: 2018年04月04日 08:39:05
  describe: api资源仓库，用于服务注册和发现
  home: /
  author: afterloe.L
  licensed: MIT Licensed

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
  instance:
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: false
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress:${random.value}}:${server.port}
    nonSecurePort: ${server.port:8080}
  client:
    filter-only-up-instances: true
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@awpaas-repository-1:8080/eureka/